# Generated by Django 6.0 on 2025-12-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_pr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ'},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Отметьте галочкой, если это правильный ответ', verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения варианта (0 - первый)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(help_text='Введите вариант ответа', max_length=500, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения вопроса (0 - первый)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Сформулируйте вопрос четко и понятно', verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание теста для участников', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='active', help_text='Активен - тест доступен участникам, Неактивен - скрыт', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(help_text='Введите понятное название теста (например, "История России 10 класс")', max_length=255, verbose_name='Название теста'),
        ),
    ]
